"""add book-topic model

Revision ID: 35271630559d
Revises: 529c8222bb0f
Create Date: 2025-11-06 21:29:31.185679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35271630559d'
down_revision = '529c8222bb0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_topics_book_id_books')),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_book_topics_topic_id_topics')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_topics')
    # ### end Alembic commands ###
