"""create topic model

Revision ID: 529c8222bb0f
Revises: 34802fe3cb73
Create Date: 2025-11-06 13:09:11.016865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529c8222bb0f'
down_revision = '34802fe3cb73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('head_image', sa.String(), nullable=False),
    sa.Column('intro', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topics')
    # ### end Alembic commands ###
